// Copyright 2026 Revington
// SPDX-License-Identifier: Apache-2.0

// Command telemetrygen generates the Prometheus alert rules and the Grafana
// dashboard pack of Ruralz Gateway from the telemetry catalog
// (internal/telemetry/catalog; docs/architecture/10-observability.md
// "Grafana dashboards and SLOs"; spec 09 requirements 71 to 73):
//
//   - rules/ruralz.rules.yaml: the M1 alert rules of OBS "Alert rules" and a
//     page and a ticket burn-rate rule for every SLO objective of 90% or more;
//   - dashboards/<uid>.json: the eight M1 dashboards.
//
// Before writing, it checks every rule and panel expression against the
// catalog: a metric that is not a catalog family (after stripping _bucket,
// _sum and _count from histograms), a histogram family selected without one
// of those suffixes, a label the family does not carry, or an enumeration
// value or histogram bound it does not export fails the run. After writing,
// it applies the same check to every Prometheus query (panel targets,
// annotations and query variables) of every dashboard file in the output
// directory, generated or not.
//
// It runs through `go generate` in its own package directory and removes
// files under rules/ and dashboards/ that carry its generated-file marker
// but are no longer generated (a renamed or dropped dashboard). The package
// test TestGeneratedUpToDate regenerates in memory and compares with the
// committed files, stale generated files included, so the test stage catches
// drift; the promtool rule tests run under the integration build tag.
package main

//go:generate go run . -out ../../../deploy/grafana

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"slices"
	"strings"
)

// rulesFile is the generated rule file's path under the output directory.
const rulesFile = "rules/ruralz.rules.yaml"

// generatedMarker, matched without regard to case, marks every file
// telemetrygen writes: the rule file header and each dashboard description.
const generatedMarker = "generated by telemetrygen"

// outputDirs are the directories under the output directory that hold
// generated files.
func outputDirs() []string { return []string{"rules", "dashboards"} }

func main() {
	out := flag.String("out", "", "output directory (deploy/grafana)")
	flag.Parse()
	if err := run(*out, os.Stderr); err != nil {
		fmt.Fprintln(os.Stderr, "telemetrygen:", err)
		os.Exit(1)
	}
}

// generated is one output file.
type generated struct {
	path string // slash-separated, relative to the output directory
	data []byte
}

// generate renders every output file in path order after checking the rule
// and dashboard tables against the catalog.
func generate() ([]generated, error) {
	defs := dashboards()
	groups := ruleGroups()
	problems := slices.Concat(checkDashboardDefs(defs), checkRules(groups, dashboardTitles()))
	if len(problems) > 0 {
		return nil, fmt.Errorf("the rule and dashboard tables do not match the telemetry catalog:\n\t%s",
			strings.Join(problems, "\n\t"))
	}
	out := []generated{{path: rulesFile, data: renderRules(groups)}}
	for _, d := range defs {
		data, err := renderDashboard(d)
		if err != nil {
			return nil, err
		}
		out = append(out, generated{path: d.file(), data: data})
	}
	slices.SortFunc(out, func(a, b generated) int { return strings.Compare(a.path, b.path) })
	return out, nil
}

// run writes the generated files under dir, then checks every dashboard
// file there; problems are listed on w.
func run(dir string, w io.Writer) error {
	if dir == "" {
		return errors.New("-out is required")
	}
	files, err := generate()
	if err != nil {
		return err
	}
	for _, f := range files {
		p := filepath.Join(dir, filepath.FromSlash(f.path))
		if err := os.MkdirAll(filepath.Dir(p), 0o750); err != nil {
			return err
		}
		if err := os.WriteFile(p, f.data, 0o644); err != nil { //nolint:gosec // G306: rules and dashboards are published, world-readable files.
			return err
		}
	}
	stale, err := staleGenerated(dir, files)
	if err != nil {
		return err
	}
	for _, rel := range stale {
		if err := os.Remove(filepath.Join(dir, filepath.FromSlash(rel))); err != nil {
			return err
		}
		if _, err := fmt.Fprintln(w, "removed stale generated file", rel); err != nil {
			return err
		}
	}
	problems, err := checkDashboardDir(filepath.Join(dir, "dashboards"))
	if err != nil {
		return err
	}
	for _, p := range problems {
		if _, err := fmt.Fprintln(w, p); err != nil {
			return err
		}
	}
	if len(problems) > 0 {
		return fmt.Errorf("%d dashboard problem(s)", len(problems))
	}
	return nil
}

// checkDashboardDir checks every *.json dashboard in dir.
func checkDashboardDir(dir string) ([]string, error) {
	names, err := filepath.Glob(filepath.Join(dir, "*.json"))
	if err != nil {
		return nil, err
	}
	slices.Sort(names)
	var out []string
	for _, name := range names {
		data, err := os.ReadFile(name) //nolint:gosec // G304: the paths come from a glob of the output directory.
		if err != nil {
			return nil, err
		}
		out = append(out, checkDashboardJSON(filepath.ToSlash(name), data)...)
	}
	return out, nil
}

// staleGenerated returns the files under dir's output directories, as
// slash-separated relative paths, that carry generatedMarker but are not
// among files: outputs of an earlier run that the tables no longer produce.
// Hand-written files lack the marker and are kept.
func staleGenerated(dir string, files []generated) ([]string, error) {
	var out []string
	for _, sub := range outputDirs() {
		entries, err := os.ReadDir(filepath.Join(dir, sub))
		if errors.Is(err, fs.ErrNotExist) {
			continue
		}
		if err != nil {
			return nil, err
		}
		for _, e := range entries {
			rel := path.Join(sub, e.Name())
			if !e.Type().IsRegular() || slices.ContainsFunc(files, func(f generated) bool { return f.path == rel }) {
				continue
			}
			data, err := os.ReadFile(filepath.Join(dir, sub, e.Name())) //nolint:gosec // G304: a directory listing of the output directory.
			if err != nil {
				return nil, err
			}
			if bytes.Contains(bytes.ToLower(data), []byte(generatedMarker)) {
				out = append(out, rel)
			}
		}
	}
	return out, nil
}
