// Copyright 2026 Revington
// SPDX-License-Identifier: Apache-2.0

package jsonval

import "strings"

// conformanceCase is one JSON conformance case, named after the
// JSONTestSuite file it reproduces (y_ must be accepted, n_ rejected, i_ is
// implementation-defined and accept holds Ruralz's decision). flag "dup"
// marks input accepted only with AllowDuplicateNames, "deep" input accepted
// only above DefaultMaxDepth.
type conformanceCase struct {
	name   string
	input  string
	accept bool
	flag   string
}

// conformanceCases returns the conformance corpus shared by the unit tests,
// the fuzz seeds and the go1.27 jsontext oracle.
func conformanceCases() []conformanceCase {
	return append([]conformanceCase{
		{"y_array_arraysWithSpaces", "[[]   ]", true, ""},
		{"y_array_empty-string", "[\"\"]", true, ""},
		{"y_array_empty", "[]", true, ""},
		{"y_array_ending_with_newline", "[\"a\"]", true, ""},
		{"y_array_false", "[false]", true, ""},
		{"y_array_heterogeneous", "[null, 1, \"1\", {}]", true, ""},
		{"y_array_null", "[null]", true, ""},
		{"y_array_with_1_and_newline", "[1\n]", true, ""},
		{"y_array_with_leading_space", " [1]", true, ""},
		{"y_array_with_several_null", "[1,null,null,null,2]", true, ""},
		{"y_array_with_trailing_space", "[2] ", true, ""},
		{"y_number", "[123e65]", true, ""},
		{"y_number_0e+1", "[0e+1]", true, ""},
		{"y_number_0e1", "[0e1]", true, ""},
		{"y_number_after_space", "[ 4]", true, ""},
		{"y_number_double_close_to_zero", "[-0.000000000000000000000000000000000000000000000000000000000000000000000000000001]", true, ""},
		{"y_number_int_with_exp", "[20e1]", true, ""},
		{"y_number_minus_zero", "[-0]", true, ""},
		{"y_number_negative_int", "[-123]", true, ""},
		{"y_number_negative_one", "[-1]", true, ""},
		{"y_number_negative_zero", "[-0]", true, ""},
		{"y_number_real_capital_e", "[1E22]", true, ""},
		{"y_number_real_capital_e_neg_exp", "[1E-2]", true, ""},
		{"y_number_real_capital_e_pos_exp", "[1E+2]", true, ""},
		{"y_number_real_exponent", "[123e45]", true, ""},
		{"y_number_real_fraction_exponent", "[123.456e78]", true, ""},
		{"y_number_real_neg_exp", "[1e-2]", true, ""},
		{"y_number_real_pos_exponent", "[1e+2]", true, ""},
		{"y_number_simple_int", "[123]", true, ""},
		{"y_number_simple_real", "[123.456789]", true, ""},
		{"y_object", "{\"asd\":\"sdf\", \"dfg\":\"fgh\"}", true, ""},
		{"y_object_basic", "{\"asd\":\"sdf\"}", true, ""},
		{"y_object_duplicated_key", "{\"a\":\"b\",\"a\":\"c\"}", false, "dup"},
		{"y_object_duplicated_key_and_value", "{\"a\":\"b\",\"a\":\"b\"}", false, "dup"},
		{"y_object_empty", "{}", true, ""},
		{"y_object_empty_key", "{\"\":0}", true, ""},
		{"y_object_escaped_null_in_key", "{\"foo\\u0000bar\": 42}", true, ""},
		{"y_object_extreme_numbers", "{ \"min\": -1.0e+28, \"max\": 1.0e+28 }", true, ""},
		{"y_object_long_strings", "{\"x\":[{\"id\": \"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\"}], \"id\": \"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\"}", true, ""},
		{"y_object_simple", "{\"a\":[]}", true, ""},
		{"y_object_string_unicode", "{\"title\":\"\\u041f\\u043e\\u043b\\u0442\\u043e\\u0440\\u0430 \\u0417\\u0435\\u043c\\u043b\\u0435\\u043a\\u043e\\u043f\\u0430\" }", true, ""},
		{"y_object_with_newlines", "{\n\"a\": \"b\"\n}", true, ""},
		{"y_string_1_2_3_bytes_UTF-8_sequences", "[\"\\u0060\\u012a\\u12AB\"]", true, ""},
		{"y_string_accepted_surrogate_pair", "[\"\\uD801\\udc37\"]", true, ""},
		{"y_string_accepted_surrogate_pairs", "[\"\\ud83d\\ude39\\ud83d\\udc8d\"]", true, ""},
		{"y_string_allowed_escapes", "[\"\\\"\\\\\\/\\b\\f\\n\\r\\t\"]", true, ""},
		{"y_string_backslash_and_u_escaped_zero", "[\"\\\\u0000\"]", true, ""},
		{"y_string_backslash_doublequotes", "[\"\\\"\"]", true, ""},
		{"y_string_comments", "[\"a/*b*/c/*d//e\"]", true, ""},
		{"y_string_double_escape_a", "[\"\\\\a\"]", true, ""},
		{"y_string_double_escape_n", "[\"\\\\n\"]", true, ""},
		{"y_string_escaped_control_character", "[\"\\u0012\"]", true, ""},
		{"y_string_escaped_noncharacter", "[\"\\uFFFF\"]", true, ""},
		{"y_string_in_array", "[\"asd\"]", true, ""},
		{"y_string_in_array_with_leading_space", "[ \"asd\"]", true, ""},
		{"y_string_last_surrogates_1_and_2", "[\"\\uDBFF\\uDFFF\"]", true, ""},
		{"y_string_nbsp_uescaped", "[\"new\\u00A0line\"]", true, ""},
		{"y_string_nonCharacterInUTF-8_U+10FFFF", "[\"\xf4\x8f\xbf\xbf\"]", true, ""},
		{"y_string_nonCharacterInUTF-8_U+FFFF", "[\"\xef\xbf\xbf\"]", true, ""},
		{"y_string_null_escape", "[\"\\u0000\"]", true, ""},
		{"y_string_one-byte-utf-8", "[\"\\u002c\"]", true, ""},
		{"y_string_pi", "[\"\xcf\x80\"]", true, ""},
		{"y_string_reservedCharacterInUTF-8_U+1BFFF", "[\"\xf0\x9b\xbf\xbf\"]", true, ""},
		{"y_string_simple_ascii", "[\"asd \"]", true, ""},
		{"y_string_space", "\" \"", true, ""},
		{"y_string_surrogates_U+1D11E_MUSICAL_SYMBOL_G_CLEF", "[\"\\uD834\\uDd1e\"]", true, ""},
		{"y_string_three-byte-utf-8", "[\"\\u0821\"]", true, ""},
		{"y_string_two-byte-utf-8", "[\"\\u0123\"]", true, ""},
		{"y_string_u+2028_line_sep", "[\"\xe2\x80\xa8\"]", true, ""},
		{"y_string_u+2029_par_sep", "[\"\xe2\x80\xa9\"]", true, ""},
		{"y_string_uEscape", "[\"\\u0061\\u30af\\u30EA\\u30b9\"]", true, ""},
		{"y_string_uescaped_newline", "[\"new\\u000Aline\"]", true, ""},
		{"y_string_unescaped_char_delete", "[\"\x7f\"]", true, ""},
		{"y_string_unicode", "[\"\\uA66D\"]", true, ""},
		{"y_string_unicodeEscapedBackslash", "[\"\\u005C\"]", true, ""},
		{"y_string_unicode_2", "[\"\xe2\x8d\x82\xe3\x88\xb4\xe2\x8d\x82\"]", true, ""},
		{"y_string_unicode_U+10FFFE_nonchar", "[\"\\uDBFF\\uDFFE\"]", true, ""},
		{"y_string_unicode_U+1FFFE_nonchar", "[\"\\uD83F\\uDFFE\"]", true, ""},
		{"y_string_unicode_U+200B_ZERO_WIDTH_SPACE", "[\"\\u200B\"]", true, ""},
		{"y_string_unicode_U+2064_invisible_plus", "[\"\\u2064\"]", true, ""},
		{"y_string_unicode_U+FDD0_nonchar", "[\"\\uFDD0\"]", true, ""},
		{"y_string_unicode_U+FFFE_nonchar", "[\"\\uFFFE\"]", true, ""},
		{"y_string_unicode_escaped_double_quote", "[\"\\u0022\"]", true, ""},
		{"y_string_utf8", "[\"\xe2\x82\xac\xf0\x9d\x84\x9e\"]", true, ""},
		{"y_string_with_del_character", "[\"a\x7fa\"]", true, ""},
		{"y_structure_lonely_false", "false", true, ""},
		{"y_structure_lonely_int", "42", true, ""},
		{"y_structure_lonely_negative_real", "-0.1", true, ""},
		{"y_structure_lonely_null", "null", true, ""},
		{"y_structure_lonely_string", "\"asd\"", true, ""},
		{"y_structure_lonely_true", "true", true, ""},
		{"y_structure_string_empty", "\"\"", true, ""},
		{"y_structure_trailing_newline", "[\"a\"]\n", true, ""},
		{"y_structure_true_in_array", "[true]", true, ""},
		{"y_structure_whitespace_array", " [] ", true, ""},
		{"n_array_1_true_without_comma", "[1 true]", false, ""},
		{"n_array_a_invalid_utf8", "[a\xe5]", false, ""},
		{"n_array_colon_instead_of_comma", "[\"\": 1]", false, ""},
		{"n_array_comma_after_close", "[\"\"],", false, ""},
		{"n_array_comma_and_number", "[,1]", false, ""},
		{"n_array_double_comma", "[1,,2]", false, ""},
		{"n_array_double_extra_comma", "[\"x\",,]", false, ""},
		{"n_array_extra_close", "[\"x\"]]", false, ""},
		{"n_array_extra_comma", "[\"\",]", false, ""},
		{"n_array_incomplete", "[\"x\"", false, ""},
		{"n_array_incomplete_invalid_value", "[x", false, ""},
		{"n_array_inner_array_no_comma", "[3[4]]", false, ""},
		{"n_array_invalid_utf8", "[\xff]", false, ""},
		{"n_array_items_separated_by_semicolon", "[1:2]", false, ""},
		{"n_array_just_comma", "[,]", false, ""},
		{"n_array_just_minus", "[-]", false, ""},
		{"n_array_missing_value", "[   , \"\"]", false, ""},
		{"n_array_newlines_unclosed", "[\"a\",\n4\n,1,", false, ""},
		{"n_array_number_and_comma", "[1,]", false, ""},
		{"n_array_number_and_several_commas", "[1,,]", false, ""},
		{"n_array_spaces_vertical_tab_formfeed", "[\"\x0ba\"\\f]", false, ""},
		{"n_array_star_inside", "[*]", false, ""},
		{"n_array_unclosed", "[\"\"", false, ""},
		{"n_array_unclosed_trailing_comma", "[1,", false, ""},
		{"n_array_unclosed_with_new_lines", "[1,\n1\n,1", false, ""},
		{"n_array_unclosed_with_object_inside", "[{}", false, ""},
		{"n_incomplete_false", "[fals]", false, ""},
		{"n_incomplete_null", "[nul]", false, ""},
		{"n_incomplete_true", "[tru]", false, ""},
		{"n_multidigit_number_then_00", "123\x00", false, ""},
		{"n_number_++", "[++1234]", false, ""},
		{"n_number_+1", "[+1]", false, ""},
		{"n_number_+Inf", "[+Inf]", false, ""},
		{"n_number_-01", "[-01]", false, ""},
		{"n_number_-1.0.", "[-1.0.]", false, ""},
		{"n_number_-2.", "[-2.]", false, ""},
		{"n_number_-NaN", "[-NaN]", false, ""},
		{"n_number_.-1", "[.-1]", false, ""},
		{"n_number_.2e-3", "[.2e-3]", false, ""},
		{"n_number_0.1.2", "[0.1.2]", false, ""},
		{"n_number_0.3e+", "[0.3e+]", false, ""},
		{"n_number_0.3e", "[0.3e]", false, ""},
		{"n_number_0.e1", "[0.e1]", false, ""},
		{"n_number_0_capital_E+", "[0E+]", false, ""},
		{"n_number_0_capital_E", "[0E]", false, ""},
		{"n_number_0e+", "[0e+]", false, ""},
		{"n_number_0e", "[0e]", false, ""},
		{"n_number_1.0e+", "[1.0e+]", false, ""},
		{"n_number_1.0e-", "[1.0e-]", false, ""},
		{"n_number_1.0e", "[1.0e]", false, ""},
		{"n_number_1_000", "[1 000.0]", false, ""},
		{"n_number_1eE2", "[1eE2]", false, ""},
		{"n_number_2.e+3", "[2.e+3]", false, ""},
		{"n_number_2.e-3", "[2.e-3]", false, ""},
		{"n_number_2.e3", "[2.e3]", false, ""},
		{"n_number_9.e+", "[9.e+]", false, ""},
		{"n_number_Inf", "[Inf]", false, ""},
		{"n_number_NaN", "[NaN]", false, ""},
		{"n_number_U+FF11_fullwidth_digit_one", "[\xef\xbc\x91]", false, ""},
		{"n_number_expression", "[1+2]", false, ""},
		{"n_number_hex_1_digit", "[0x1]", false, ""},
		{"n_number_hex_2_digits", "[0x42]", false, ""},
		{"n_number_infinity", "[Infinity]", false, ""},
		{"n_number_invalid+-", "[0e+-1]", false, ""},
		{"n_number_invalid-negative-real", "[-123.123foo]", false, ""},
		{"n_number_invalid-utf-8-in-bigger-int", "[123\xe5]", false, ""},
		{"n_number_invalid-utf-8-in-exponent", "[1e1\xe5]", false, ""},
		{"n_number_invalid-utf-8-in-int", "[0\xe5]", false, ""},
		{"n_number_minus_infinity", "[-Infinity]", false, ""},
		{"n_number_minus_sign_with_trailing_garbage", "[-foo]", false, ""},
		{"n_number_minus_space_1", "[- 1]", false, ""},
		{"n_number_neg_int_starting_with_zero", "[-012]", false, ""},
		{"n_number_neg_real_without_int_part", "[-.123]", false, ""},
		{"n_number_neg_with_garbage_at_end", "[-1x]", false, ""},
		{"n_number_real_garbage_after_e", "[1ea]", false, ""},
		{"n_number_real_with_invalid_utf8_after_e", "[1e\xe5]", false, ""},
		{"n_number_real_without_fractional_part", "[1.]", false, ""},
		{"n_number_starting_with_dot", "[.123]", false, ""},
		{"n_number_with_alpha", "[1.2a-3]", false, ""},
		{"n_number_with_alpha_char", "[1.8011670033376514H-308]", false, ""},
		{"n_number_with_leading_zero", "[012]", false, ""},
		{"n_object_bad_value", "[\"x\", truth]", false, ""},
		{"n_object_bracket_key", "{[: \"x\"}", false, ""},
		{"n_object_comma_instead_of_colon", "{\"x\", null}", false, ""},
		{"n_object_double_colon", "{\"x\"::\"b\"}", false, ""},
		{"n_object_emoji", "{\xf0\x9f\x87\xa8\xf0\x9f\x87\xad}", false, ""},
		{"n_object_garbage_at_end", "{\"a\":\"a\" 123}", false, ""},
		{"n_object_key_with_single_quotes", "{key: 'value'}", false, ""},
		{"n_object_lone_continuation_byte_in_key_and_trailing_comma", "{\"\xb9\":\"0\",}", false, ""},
		{"n_object_missing_colon", "{\"a\" b}", false, ""},
		{"n_object_missing_key", "{:\"b\"}", false, ""},
		{"n_object_missing_semicolon", "{\"a\" \"b\"}", false, ""},
		{"n_object_missing_value", "{\"a\":", false, ""},
		{"n_object_no-colon", "{\"a\"", false, ""},
		{"n_object_non_string_key", "{1:1}", false, ""},
		{"n_object_non_string_key_but_huge_number_instead", "{9999E9999:1}", false, ""},
		{"n_object_repeated_null_null", "{null:null,null:null}", false, ""},
		{"n_object_several_trailing_commas", "{\"id\":0,,,,,}", false, ""},
		{"n_object_single_quote", "{'a':0}", false, ""},
		{"n_object_trailing_comma", "{\"id\":0,}", false, ""},
		{"n_object_trailing_comment", "{\"a\":\"b\"}/**/", false, ""},
		{"n_object_trailing_comment_open", "{\"a\":\"b\"}/**//", false, ""},
		{"n_object_trailing_comment_slash_open", "{\"a\":\"b\"}//", false, ""},
		{"n_object_trailing_comment_slash_open_incomplete", "{\"a\":\"b\"}/", false, ""},
		{"n_object_two_commas_in_a_row", "{\"a\":\"b\",,\"c\":\"d\"}", false, ""},
		{"n_object_unquoted_key", "{a: \"b\"}", false, ""},
		{"n_object_unterminated-value", "{\"a\":\"a", false, ""},
		{"n_object_with_single_string", "{ \"foo\" : \"bar\", \"a\" }", false, ""},
		{"n_object_with_trailing_garbage", "{\"a\":\"b\"}#", false, ""},
		{"n_single_space", " ", false, ""},
		{"n_string_1_surrogate_then_escape", "[\"\\uD800\\\"]", false, ""},
		{"n_string_1_surrogate_then_escape_u", "[\"\\uD800\\u\"]", false, ""},
		{"n_string_1_surrogate_then_escape_u1", "[\"\\uD800\\u1\"]", false, ""},
		{"n_string_1_surrogate_then_escape_u1x", "[\"\\uD800\\u1x\"]", false, ""},
		{"n_string_accentuated_char_no_quotes", "[\xc3\xa9]", false, ""},
		{"n_string_backslash_00", "[\"\\\x00\"]", false, ""},
		{"n_string_escape_x", "[\"\\x00\"]", false, ""},
		{"n_string_escaped_backslash_bad", "[\"\\\\\\\"]", false, ""},
		{"n_string_escaped_ctrl_char_tab", "[\"\\\t\"]", false, ""},
		{"n_string_escaped_emoji", "[\"\\\xf0\x9f\x8c\x80\"]", false, ""},
		{"n_string_incomplete_escape", "[\"\\\"]", false, ""},
		{"n_string_incomplete_escaped_character", "[\"\\u00A\"]", false, ""},
		{"n_string_incomplete_surrogate", "[\"\\uD834\\uDd\"]", false, ""},
		{"n_string_incomplete_surrogate_escape_invalid", "[\"\\uD800\\uD800\\x\"]", false, ""},
		{"n_string_invalid-utf-8-in-escape", "[\"\\u\xe5\"]", false, ""},
		{"n_string_invalid_backslash_esc", "[\"\\a\"]", false, ""},
		{"n_string_invalid_unicode_escape", "[\"\\uqqqq\"]", false, ""},
		{"n_string_invalid_utf8_after_escape", "[\"\\\xe5\"]", false, ""},
		{"n_string_leading_uescaped_thinspace", "[\\u0020\"asd\"]", false, ""},
		{"n_string_no_quotes_with_bad_escape", "[\\n]", false, ""},
		{"n_string_single_doublequote", "\"", false, ""},
		{"n_string_single_quote", "['single quote']", false, ""},
		{"n_string_single_string_no_double_quotes", "abc", false, ""},
		{"n_string_start_escape_unclosed", "[\"\\", false, ""},
		{"n_string_unescaped_ctrl_char", "[\"a\x00a\"]", false, ""},
		{"n_string_unescaped_newline", "[\"new\nline\"]", false, ""},
		{"n_string_unescaped_tab", "[\"\t\"]", false, ""},
		{"n_string_unicode_CapitalU", "\"\\UA66D\"", false, ""},
		{"n_string_with_trailing_garbage", "\"\"x", false, ""},
		{"n_structure_U+2060_word_joined", "[\xe2\x81\xa0]", false, ""},
		{"n_structure_UTF8_BOM_no_data", "\xef\xbb\xbf", false, ""},
		{"n_structure_angle_bracket_.", "<.>", false, ""},
		{"n_structure_angle_bracket_null", "[<null>]", false, ""},
		{"n_structure_array_trailing_garbage", "[1]x", false, ""},
		{"n_structure_array_with_extra_array_close", "[1]]", false, ""},
		{"n_structure_array_with_unclosed_string", "[\"asd]", false, ""},
		{"n_structure_ascii-unicode-identifier", "a\xc3\xa5", false, ""},
		{"n_structure_capitalized_True", "[True]", false, ""},
		{"n_structure_close_unopened_array", "1]", false, ""},
		{"n_structure_comma_instead_of_closing_brace", "{\"x\": true,", false, ""},
		{"n_structure_double_array", "[][]", false, ""},
		{"n_structure_end_array", "]", false, ""},
		{"n_structure_incomplete_UTF8_BOM", "\xef\xbb{}", false, ""},
		{"n_structure_lone-invalid-utf-8", "\xe5", false, ""},
		{"n_structure_lone-open-bracket", "[", false, ""},
		{"n_structure_no_data", "", false, ""},
		{"n_structure_null-byte-outside-string", "[\x00]", false, ""},
		{"n_structure_number_with_trailing_garbage", "2@", false, ""},
		{"n_structure_object_followed_by_closing_object", "{}}", false, ""},
		{"n_structure_object_unclosed_no_value", "{\"\":", false, ""},
		{"n_structure_object_with_comment", "{\"a\":/*comment*/\"b\"}", false, ""},
		{"n_structure_object_with_trailing_garbage", "{\"a\": true} \"x\"", false, ""},
		{"n_structure_open_array_apostrophe", "['", false, ""},
		{"n_structure_open_array_comma", "[,", false, ""},
		{"n_structure_open_array_open_object", "[{", false, ""},
		{"n_structure_open_array_open_string", "[\"a", false, ""},
		{"n_structure_open_array_string", "[\"a\"", false, ""},
		{"n_structure_open_object", "{", false, ""},
		{"n_structure_open_object_close_array", "{]", false, ""},
		{"n_structure_open_object_comma", "{,", false, ""},
		{"n_structure_open_object_open_array", "{[", false, ""},
		{"n_structure_open_object_open_string", "{\"a", false, ""},
		{"n_structure_open_object_string_with_apostrophes", "{'a'", false, ""},
		{"n_structure_open_open", "[\"\\{[\"\\{[\"\\{[\"\\{", false, ""},
		{"n_structure_single_eacute", "\xe9", false, ""},
		{"n_structure_single_star", "*", false, ""},
		{"n_structure_trailing_#", "{\"a\":\"b\"}#{}", false, ""},
		{"n_structure_uescaped_LF_before_string", "[\\u000A\"\"]", false, ""},
		{"n_structure_unclosed_array", "[1", false, ""},
		{"n_structure_unclosed_array_partial_null", "[ false, nul", false, ""},
		{"n_structure_unclosed_array_unfinished_false", "[ true, fals", false, ""},
		{"n_structure_unclosed_array_unfinished_true", "[ false, tru", false, ""},
		{"n_structure_unclosed_object", "{\"asd\":\"asd\"", false, ""},
		{"n_structure_unicode-identifier", "\xc3\xa5", false, ""},
		{"n_structure_whitespace_U+2060_word_joiner", "[\xe2\x81\xa0]", false, ""},
		{"n_structure_whitespace_formfeed", "[\x0c]", false, ""},
		{"i_number_double_huge_neg_exp", "[123.456e-789]", true, ""},
		{"i_number_huge_exp", "[0.4e0066999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999969999999006]", true, ""},
		{"i_number_neg_int_huge_exp", "[-1e+9999]", true, ""},
		{"i_number_pos_double_huge_exp", "[1.5e+9999]", true, ""},
		{"i_number_real_neg_overflow", "[-123123e100000]", true, ""},
		{"i_number_real_pos_overflow", "[123123e100000]", true, ""},
		{"i_number_real_underflow", "[123e-10000000]", true, ""},
		{"i_number_too_big_neg_int", "[-123123123123123123123123123123]", true, ""},
		{"i_number_too_big_pos_int", "[100000000000000000000]", true, ""},
		{"i_number_very_big_negative_int", "[-237462374673276894279832749832423479823246327846]", true, ""},
		{"i_object_key_lone_2nd_surrogate", "{\"\\uDFAA\":0}", false, ""},
		{"i_string_1st_surrogate_but_2nd_missing", "[\"\\uDADA\"]", false, ""},
		{"i_string_1st_valid_surrogate_2nd_invalid", "[\"\\uD888\\u1234\"]", false, ""},
		{"i_string_UTF-16LE_with_BOM", "\xff\xfe[\x00\"\x00\xe9\x00\"\x00]\x00", false, ""},
		{"i_string_UTF-8_invalid_sequence", "[\"\xe6\x97\xa5\xd1\x88\xfa\"]", false, ""},
		{"i_string_UTF8_surrogate_U+D800", "[\"\xed\xa0\x80\"]", false, ""},
		{"i_string_incomplete_surrogate_and_escape_valid", "[\"\\uD800\\n\"]", false, ""},
		{"i_string_incomplete_surrogate_pair", "[\"\\uDd1ea\"]", false, ""},
		{"i_string_incomplete_surrogates_escape_valid", "[\"\\uD800\\uD800\\n\"]", false, ""},
		{"i_string_invalid_lonely_surrogate", "[\"\\ud800\"]", false, ""},
		{"i_string_invalid_surrogate", "[\"\\ud800abc\"]", false, ""},
		{"i_string_invalid_utf-8", "[\"\xff\"]", false, ""},
		{"i_string_inverted_surrogates_U+1D11E", "[\"\\uDd1e\\uD834\"]", false, ""},
		{"i_string_iso_latin_1", "[\"\xe9\"]", false, ""},
		{"i_string_lone_second_surrogate", "[\"\\uDFAA\"]", false, ""},
		{"i_string_lone_utf8_continuation_byte", "[\"\x81\"]", false, ""},
		{"i_string_not_in_unicode_range", "[\"\xf4\xbf\xbf\xbf\"]", false, ""},
		{"i_string_overlong_sequence_2_bytes", "[\"\xc0\xaf\"]", false, ""},
		{"i_string_overlong_sequence_6_bytes", "[\"\xfc\x83\xbf\xbf\xbf\xbf\"]", false, ""},
		{"i_string_overlong_sequence_6_bytes_null", "[\"\xfc\x80\x80\x80\x80\x80\"]", false, ""},
		{"i_string_truncated-utf-8", "[\"\xe0\xff\"]", false, ""},
		{"i_string_utf16BE_no_BOM", "\x00[\x00\"\x00\xe9\x00\"\x00]", false, ""},
		{"i_string_utf16LE_no_BOM", "[\x00\"\x00\xe9\x00\"\x00]\x00", false, ""},
		{"i_structure_UTF-8_BOM_empty_object", "\xef\xbb\xbf{}", false, ""},
	},
		conformanceCase{"n_structure_100000_opening_arrays", strings.Repeat("[", 100000), false, ""},
		conformanceCase{"n_structure_open_array_object", strings.Repeat(`[{"":`, 5000) + "\n", false, ""},
		conformanceCase{"i_structure_500_nested_arrays", strings.Repeat("[", 500) + strings.Repeat("]", 500), false, "deep"},
	)
}
