// Copyright 2026 Revington
// SPDX-License-Identifier: Apache-2.0

// Package schema embeds the published JSON Schema (draft 2020-12) of the
// Ruralz configuration resources, so every source-loading path validates
// against identical bytes. The files are generated by
// internal/tool/schemagen from pkg/config/v1alpha1; run `make generate`.
package schema

import (
	"bytes"
	"embed"
	"io/fs"
)

//go:embed ruralz/v1alpha1/authoring.schema.json
var authoringV1alpha1 []byte

//go:embed ruralz/v1alpha1/rendered.schema.json
var renderedV1alpha1 []byte

//go:embed ruralz
var files embed.FS

// AuthoringV1alpha1 returns the authoring view of the ruralz/v1alpha1
// schema, used by editors and for raw source files: substitutable
// non-string scalars also accept a ${VAR} expression.
func AuthoringV1alpha1() []byte {
	return bytes.Clone(authoringV1alpha1)
}

// RenderedV1alpha1 returns the strict rendered view of the ruralz/v1alpha1
// schema, which validates documents after substitution.
func RenderedV1alpha1() []byte {
	return bytes.Clone(renderedV1alpha1)
}

// FS returns the schema files, rooted at ruralz/<apiVersion>/.
func FS() fs.FS {
	return files
}
