// Copyright 2026 Revington
// SPDX-License-Identifier: Apache-2.0

package completion

import (
	"bytes"
	"fmt"
	"strings"
)

// writeBash renders the bash script (spec 10 req 108): a _<program>
// function over COMP_WORDS and COMP_CWORD registered with
// `complete -o bashdefault -o default`. The command table is data in
// associative arrays (bash 4.0), read by one fixed algorithm that mirrors
// the dispatcher: word 1 is a noun or a command, word 2 a noun's verb,
// flags and positionals follow in any order, "--" ends the flags, and a
// flag's value is the next word or follows "=".
func writeBash(b *bytes.Buffer, m *model) {
	p, fn := m.program, "_"+m.ident
	reply := "__" + m.ident + "_reply"
	fmt.Fprintf(b, `# bash completion for %[1]s
# Generated by '%[1]s completion bash'; do not edit.
# Install: source <(%[1]s completion bash)
# Needs bash 4.2 or newer.

# %[2]s KIND: completes $cur from the caller as KIND: file, dir, none or
# words:<values>.
%[2]s() {
    case $1 in
    file)
        compopt -o filenames 2>/dev/null
        mapfile -t COMPREPLY < <(compgen -f -- "$cur")
        ;;
    dir)
        compopt -o filenames +o default +o bashdefault 2>/dev/null
        mapfile -t COMPREPLY < <(compgen -d -- "$cur")
        ;;
    words:*)
        compopt +o default +o bashdefault 2>/dev/null
        mapfile -t COMPREPLY < <(compgen -W "${1#words:}" -- "$cur")
        ;;
    *)
        compopt +o default +o bashdefault 2>/dev/null
        COMPREPLY=()
        ;;
    esac
}

%[3]s() {
`, p, reply, fn)

	b.WriteString("    local -A verbs=(\n")
	for _, n := range m.nouns {
		fmt.Fprintf(b, "        [%s]=%s\n", n.name, bashQuote(joinNames(n.verbs)))
	}
	b.WriteString("    )\n    local -A flags=(\n")
	for _, c := range m.cmds {
		names := make([]string, 0, len(c.flags))
		for _, f := range c.flags {
			names = append(names, "--"+f.name)
		}
		fmt.Fprintf(b, "        [%s]=%s\n", bashQuote(c.id), bashQuote(strings.Join(names, " ")))
	}
	b.WriteString("    )\n    local -A values=(\n")
	for _, c := range m.cmds {
		for _, f := range c.flags {
			if !f.takesValue {
				continue
			}
			key := c.id + " --" + f.name
			fmt.Fprintf(b, "        [%s]=%s\n", bashQuote(key), bashQuote(f.value.token()))
			for i, md := range f.modes {
				fmt.Fprintf(b, "        [%s]=%s\n", bashQuote(fmt.Sprintf("%s %d", key, i+1)), bashQuote(md.value.token()))
			}
		}
	}
	b.WriteString("    )\n    local -A modes=(\n")
	for _, c := range m.cmds {
		for _, f := range c.flags {
			for i, md := range f.modes {
				when := make([]string, 0, len(md.when))
				for _, w := range md.when {
					when = append(when, "--"+w)
				}
				fmt.Fprintf(b, "        [%s]=%s\n", bashQuote(fmt.Sprintf("%s --%s %d", c.id, f.name, i+1)),
					bashQuote(" "+strings.Join(when, " ")+" "))
			}
		}
	}
	b.WriteString("    )\n    local -A args=(\n")
	for _, c := range m.cmds {
		for i, a := range c.args {
			key := fmt.Sprintf("%s %d", c.id, i)
			if a.repeat {
				key = c.id + " *"
			}
			fmt.Fprintf(b, "        [%s]=%s\n", bashQuote(key), bashQuote(a.value.token()))
		}
	}
	b.WriteString("    )\n")
	tops := make([]string, 0, len(m.tops))
	helps := make([]string, 0, len(m.tops))
	for _, t := range m.tops {
		tops = append(tops, t.name)
		if t.name != helpWord {
			helps = append(helps, t.name)
		}
	}
	fmt.Fprintf(b, "    local top=%s\n", bashQuote(strings.Join(tops, " ")))
	fmt.Fprintf(b, "    local helptop=%s\n", bashQuote(strings.Join(helps, " ")))
	fmt.Fprintf(b, `    local cur=${COMP_WORDS[COMP_CWORD]} prev= pfx= cmd= w= m= kind= i=0 n=0 start=2 ddash=0 seen=' '
    COMPREPLY=()
    ((COMP_CWORD > 0)) && prev=${COMP_WORDS[COMP_CWORD-1]}
    # "--flag=value" arrives as three words when "=" is in COMP_WORDBREAKS.
    if [[ $cur == = ]]; then
        cur=
    elif [[ $prev == = ]] && ((COMP_CWORD > 1)); then
        prev=${COMP_WORDS[COMP_CWORD-2]}
    elif [[ $cur == -?*=* ]]; then
        prev=${cur%%%%=*}
        pfx=$prev=
        cur=${cur#*=}
    fi
    if ((COMP_CWORD == 1)); then
        %[1]s "words:$top"
        return 0
    fi
    w=${COMP_WORDS[1]}
    if [[ $w == help ]]; then
        if ((COMP_CWORD == 2)); then
            %[1]s "words:$helptop"
        elif ((COMP_CWORD == 3)) && [[ -n ${COMP_WORDS[2]} && -n ${verbs[${COMP_WORDS[2]}]+set} ]]; then
            %[1]s "words:${verbs[${COMP_WORDS[2]}]}"
        else
            %[1]s none
        fi
        return 0
    fi
    if [[ -n $w && -n ${verbs[$w]+set} ]]; then
        if ((COMP_CWORD == 2)); then
            %[1]s "words:${verbs[$w]}"
            return 0
        fi
        cmd="$w ${COMP_WORDS[2]}"
        start=3
    else
        cmd=$w
    fi
    if [[ -z $cmd || -z ${flags[$cmd]+set} ]]; then
        %[1]s none
        return 0
    fi
    for ((i = start; i < COMP_CWORD; i++)); do
        w=${COMP_WORDS[i]}
        if ((ddash)); then
            n=$((n + 1))
        elif [[ $w == -- ]]; then
            ddash=1
        elif [[ $w == = ]]; then
            i=$((i + 1))
        elif [[ $w == -?* ]]; then
            m=${w#-}
            m=--${m#-}
            m=${m%%%%=*}
            seen+="$m "
            if [[ $w != *=* && ${COMP_WORDS[i+1]} != = && -n ${values["$cmd $m"]+set} ]]; then
                i=$((i + 1))
            fi
        else
            n=$((n + 1))
        fi
    done
    if ((!ddash)) && [[ $prev == -?* ]]; then
        m=${prev#-}
        m=--${m#-}
        if [[ -n ${values["$cmd $m"]+set} ]]; then
            kind=${values["$cmd $m"]}
            for ((i = 1; ; i++)); do
                [[ -n ${modes["$cmd $m $i"]+set} ]] || break
                for w in ${modes["$cmd $m $i"]}; do
                    if [[ $seen == *" $w "* ]]; then
                        kind=${values["$cmd $m $i"]}
                        break 2
                    fi
                done
            done
            %[1]s "$kind"
            if [[ -n $pfx ]]; then
                COMPREPLY=("${COMPREPLY[@]/#/$pfx}")
            fi
            return 0
        fi
    fi
    if ((!ddash)) && [[ $cur == -* ]]; then
        %[1]s "words:${flags[$cmd]}"
        return 0
    fi
    kind=${args["$cmd $n"]-${args["$cmd *"]-}}
    if [[ -n $kind ]]; then
        %[1]s "$kind"
    elif ((!ddash)); then
        %[1]s "words:${flags[$cmd]}"
    else
        %[1]s none
    fi
    return 0
}

complete -o bashdefault -o default -F %[2]s %[3]s
`, reply, fn, p)
}

// bashQuote single-quotes s for bash.
func bashQuote(s string) string { return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'" }

func joinNames(ws []word) string {
	names := make([]string, 0, len(ws))
	for _, w := range ws {
		names = append(names, w.name)
	}
	return strings.Join(names, " ")
}
