// Copyright 2026 Revington
// SPDX-License-Identifier: Apache-2.0

package completion

import (
	"bytes"
	"fmt"
	"slices"
	"strings"

	"github.com/ravindu-rev/ruralz/internal/cli/command"
)

// writeFish renders the fish script (spec 10 req 108): `complete -c`
// lines whose conditions use __fish_use_subcommand and
// __fish_seen_subcommand_from; file completion is off except where a
// value or positional completes files. An enum flag with modes gets one
// line per mode, told apart with __fish_contains_opt.
func writeFish(b *bytes.Buffer, m *model) {
	p := m.program
	fmt.Fprintf(b, `# fish completion for %[1]s
# Generated by '%[1]s completion fish'; do not edit.
# Install: %[1]s completion fish > ~/.config/fish/completions/%[1]s.fish

complete -c %[1]s -f

# Nouns and commands.
`, p)
	var helps []string
	for _, t := range m.tops {
		fmt.Fprintf(b, "complete -c %s -n __fish_use_subcommand -a %s -d %s\n", p, t.name, fishQuote(t.desc))
		if t.name != helpWord {
			helps = append(helps, t.name)
		}
	}
	fmt.Fprintf(b, "\n# %s help <command>\n", p)
	helpCond := fmt.Sprintf("__fish_seen_subcommand_from %s; and not __fish_seen_subcommand_from %s",
		helpWord, strings.Join(helps, " "))
	for _, t := range m.tops {
		if t.name != helpWord {
			fmt.Fprintf(b, "complete -c %s -n %s -a %s -d %s\n", p, fishQuote(helpCond), t.name, fishQuote(t.desc))
		}
	}
	for _, n := range m.nouns {
		fmt.Fprintf(b, "\n# %s %s <verb>\n", p, n.name)
		cond := fmt.Sprintf("__fish_seen_subcommand_from %s; and not __fish_seen_subcommand_from %s",
			n.name, joinNames(n.verbs))
		for _, v := range n.verbs {
			fmt.Fprintf(b, "complete -c %s -n %s -a %s -d %s\n", p, fishQuote(cond), v.name, fishQuote(v.desc))
		}
	}
	for _, c := range m.cmds {
		fmt.Fprintf(b, "\n# %s %s\n", p, c.id)
		conds := make([]string, 0, len(c.path))
		for _, w := range c.path {
			conds = append(conds, "__fish_seen_subcommand_from "+w)
		}
		cond := strings.Join(conds, "; and ")
		for _, f := range c.flags {
			writeFishFlag(b, p, cond, f)
		}
		// Positions are not told apart: every positional's completion is
		// offered, each distinct line once.
		var lines []string
		for _, a := range c.args {
			opts := fishValue(a.value)
			if opts == "" {
				continue
			}
			line := fmt.Sprintf("complete -c %s -n %s %s", p, fishQuote(cond), opts)
			if a.value.complete == command.CompleteValues {
				line += " -d " + fishQuote(a.desc)
			}
			if !slices.Contains(lines, line) {
				lines = append(lines, line)
				fmt.Fprintln(b, line)
			}
		}
	}
}

// writeFishFlag renders the lines of one flag.
func writeFishFlag(b *bytes.Buffer, p, cond string, f flagModel) {
	desc := fishQuote(f.desc)
	if !f.takesValue {
		fmt.Fprintf(b, "complete -c %s -n %s -l %s -d %s\n", p, fishQuote(cond), f.name, desc)
		return
	}
	if len(f.modes) == 0 {
		fmt.Fprintf(b, "complete -c %s -n %s -l %s %s -d %s\n", p, fishQuote(cond), f.name, fishFlagValue(f.value), desc)
		return
	}
	var earlier []string
	for _, md := range f.modes {
		c := cond
		for _, e := range earlier {
			c += "; and not __fish_contains_opt " + e
		}
		when := strings.Join(md.when, " ")
		c += "; and __fish_contains_opt " + when
		fmt.Fprintf(b, "complete -c %s -n %s -l %s %s -d %s\n", p, fishQuote(c), f.name, fishFlagValue(md.value), desc)
		earlier = append(earlier, when)
	}
	c := cond + "; and not __fish_contains_opt " + strings.Join(earlier, " ")
	fmt.Fprintf(b, "complete -c %s -n %s -l %s %s -d %s\n", p, fishQuote(c), f.name, fishFlagValue(f.value), desc)
}

// fishFlagValue is the option part of a flag taking a value.
func fishFlagValue(v valueKind) string {
	if v.token() == "file" {
		return "-r -F"
	}
	if opts := fishValue(v); opts != "" {
		return "-x " + opts
	}
	return "-x"
}

// fishValue is the argument part completing a value, or "" for none.
func fishValue(v valueKind) string {
	switch v.token() {
	case "file":
		return "-F"
	case "dir":
		return "-a '(__fish_complete_directories)'"
	case "none":
		return ""
	default:
		return "-a " + fishQuote(strings.Join(v.values, " "))
	}
}

// fishQuote single-quotes s for fish.
func fishQuote(s string) string {
	return "'" + strings.NewReplacer(`\`, `\\`, `'`, `\'`).Replace(s) + "'"
}
