// Copyright 2026 Revington
// SPDX-License-Identifier: Apache-2.0

package completion

import (
	"bytes"
	"fmt"
	"strings"
)

// writePowerShell renders the PowerShell script (spec 10 req 108):
// Register-ArgumentCompleter -Native with a script block returning
// [System.Management.Automation.CompletionResult] objects. The command
// table is data in hashtables read by the same algorithm as the bash
// script. File values return nothing, so PowerShell completes paths;
// other kinds return an empty string when nothing matches, which keeps
// PowerShell from completing paths.
//
// The empty string is a documented trade-off (cobra's script does the
// same): a CompletionResult cannot have an empty text, so
// CommandCompletion.CompleteInput throws when it converts the empty
// string (pwsh 7.4 and 7.6: "the value of argument completionText is
// null"). PSReadLine swallows the exception and shows no completion,
// which is the intent; another host calling TabExpansion2, such as an
// editor, sees the exception instead. Returning nothing would fall back
// to path completion. TestPowerShellBehaviorReq107 pins this behavior.
func writePowerShell(b *bytes.Buffer, m *model) {
	p := m.program
	fmt.Fprintf(b, `# PowerShell completion for %[1]s
# Generated by '%[1]s completion powershell'; do not edit.
# Install: %[1]s completion powershell | Out-String | Invoke-Expression

Register-ArgumentCompleter -Native -CommandName %[2]s -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $top = [ordered]@{
`, p, psQuote(p))
	for _, t := range m.tops {
		fmt.Fprintf(b, "        %s = %s\n", psQuote(t.name), psQuote(psTip(t.desc, t.name)))
	}
	b.WriteString("    }\n    $verbs = @{\n")
	for _, n := range m.nouns {
		fmt.Fprintf(b, "        %s = [ordered]@{\n", psQuote(n.name))
		for _, v := range n.verbs {
			fmt.Fprintf(b, "            %s = %s\n", psQuote(v.name), psQuote(psTip(v.desc, v.name)))
		}
		b.WriteString("        }\n")
	}
	b.WriteString("    }\n    $flags = @{\n")
	for _, c := range m.cmds {
		fmt.Fprintf(b, "        %s = [ordered]@{\n", psQuote(c.id))
		for _, f := range c.flags {
			fmt.Fprintf(b, "            %s = %s\n", psQuote("--"+f.name), psQuote(psTip(f.desc, "--"+f.name)))
		}
		b.WriteString("        }\n")
	}
	b.WriteString("    }\n    $values = @{\n")
	for _, c := range m.cmds {
		for _, f := range c.flags {
			if !f.takesValue {
				continue
			}
			key := c.id + " --" + f.name
			fmt.Fprintf(b, "        %s = %s\n", psQuote(key), psQuote(f.value.token()))
			for i, md := range f.modes {
				fmt.Fprintf(b, "        %s = %s\n", psQuote(fmt.Sprintf("%s %d", key, i+1)), psQuote(md.value.token()))
			}
		}
	}
	b.WriteString("    }\n    $modes = @{\n")
	for _, c := range m.cmds {
		for _, f := range c.flags {
			for i, md := range f.modes {
				when := make([]string, 0, len(md.when))
				for _, w := range md.when {
					when = append(when, psQuote("--"+w))
				}
				fmt.Fprintf(b, "        %s = @(%s)\n", psQuote(fmt.Sprintf("%s --%s %d", c.id, f.name, i+1)),
					strings.Join(when, ", "))
			}
		}
	}
	b.WriteString("    }\n    $positionals = @{\n")
	for _, c := range m.cmds {
		for i, a := range c.args {
			key := fmt.Sprintf("%s %d", c.id, i)
			if a.repeat {
				key = c.id + " *"
			}
			fmt.Fprintf(b, "        %s = %s\n", psQuote(key), psQuote(a.value.token()))
		}
	}
	b.WriteString(`    }

    $words = [System.Collections.Generic.List[string]]::new()
    foreach ($element in $commandAst.CommandElements) {
        if ($element.Extent.StartOffset -lt $cursorPosition) {
            $words.Add($element.Extent.Text)
        }
    }
    if ($wordToComplete -ne '' -and $words.Count -gt 0) {
        $words.RemoveAt($words.Count - 1)
    }
    $cur = $wordToComplete
    $prefix = ''
    $prev = ''
    if ($words.Count -gt 1) {
        $prev = $words[$words.Count - 1]
    }
    if ($cur -like '-?*=*') {
        $prev = $cur.Substring(0, $cur.IndexOf('='))
        $prefix = $prev + '='
        $cur = $cur.Substring($cur.IndexOf('=') + 1)
    }

    $emitWords = {
        param($table, [string]$type)
        $found = $false
        foreach ($entry in $table.GetEnumerator()) {
            if ($entry.Key.StartsWith($cur, [System.StringComparison]::OrdinalIgnoreCase)) {
                $found = $true
                [System.Management.Automation.CompletionResult]::new($prefix + $entry.Key, $entry.Key, $type, $entry.Value)
            }
        }
        if (-not $found) {
            ''
        }
    }
    $emit = {
        param([string]$kind)
        if ($kind -eq 'file') {
            return
        }
        if ($kind -eq 'dir') {
            $sep = [Math]::Max($cur.LastIndexOf('/'), $cur.LastIndexOf('\'))
            $base = ''
            if ($sep -ge 0) {
                $base = $cur.Substring(0, $sep + 1)
            }
            $found = $false
            foreach ($item in @(Get-ChildItem -Path ($cur + '*') -Directory -Force -ErrorAction SilentlyContinue)) {
                $found = $true
                $text = $base + $item.Name
                if ($text -match '[\s''"]') {
                    $text = "'" + $text.Replace("'", "''") + "'"
                }
                [System.Management.Automation.CompletionResult]::new($prefix + $text, $item.Name, 'ProviderContainer', $item.Name)
            }
            if (-not $found) {
                ''
            }
            return
        }
        if ($kind.StartsWith('words:')) {
            $table = [ordered]@{}
            foreach ($w in $kind.Substring(6).Split(' ')) {
                $table[$w] = $w
            }
            & $emitWords $table 'ParameterValue'
            return
        }
        ''
    }

    if ($words.Count -lt 2) {
        & $emitWords $top 'ParameterValue'
        return
    }
    $w = $words[1]
    if ($w -eq 'help') {
        if ($words.Count -eq 2) {
            $helpTop = [ordered]@{}
            foreach ($entry in $top.GetEnumerator()) {
                if ($entry.Key -ne 'help') {
                    $helpTop[$entry.Key] = $entry.Value
                }
            }
            & $emitWords $helpTop 'ParameterValue'
        } elseif ($words.Count -eq 3 -and $verbs.ContainsKey($words[2])) {
            & $emitWords $verbs[$words[2]] 'ParameterValue'
        } else {
            ''
        }
        return
    }
    $cmd = $w
    $start = 2
    if ($verbs.ContainsKey($w)) {
        if ($words.Count -eq 2) {
            & $emitWords $verbs[$w] 'ParameterValue'
            return
        }
        $cmd = $w + ' ' + $words[2]
        $start = 3
    }
    if (-not $flags.ContainsKey($cmd)) {
        ''
        return
    }

    $n = 0
    $ddash = $false
    $seen = @{}
    for ($i = $start; $i -lt $words.Count; $i++) {
        $t = $words[$i]
        if ($ddash) {
            $n++
            continue
        }
        if ($t -eq '--') {
            $ddash = $true
            continue
        }
        if ($t -like '-?*') {
            $name = '--' + $t.TrimStart('-')
            $eq = $name.IndexOf('=')
            if ($eq -ge 0) {
                $name = $name.Substring(0, $eq)
            }
            $seen[$name] = $true
            if ($eq -lt 0 -and $values.ContainsKey("$cmd $name")) {
                $i++
            }
            continue
        }
        $n++
    }

    if (-not $ddash -and $prev -like '-?*') {
        $name = '--' + $prev.TrimStart('-')
        if ($values.ContainsKey("$cmd $name")) {
            $kind = $values["$cmd $name"]
            for ($m = 1; $modes.ContainsKey("$cmd $name $m"); $m++) {
                $hit = $false
                foreach ($when in $modes["$cmd $name $m"]) {
                    if ($seen.ContainsKey($when)) {
                        $hit = $true
                    }
                }
                if ($hit) {
                    $kind = $values["$cmd $name $m"]
                    break
                }
            }
            & $emit $kind
            return
        }
    }
    if (-not $ddash -and $cur -like '-*') {
        & $emitWords $flags[$cmd] 'ParameterName'
        return
    }
    $kind = $positionals["$cmd $n"]
    if ($null -eq $kind) {
        $kind = $positionals["$cmd *"]
    }
    if ($null -ne $kind) {
        & $emit $kind
    } elseif (-not $ddash) {
        & $emitWords $flags[$cmd] 'ParameterName'
    } else {
        ''
    }
}
`)
}

// psQuote single-quotes s for PowerShell.
func psQuote(s string) string { return "'" + strings.ReplaceAll(s, "'", "''") + "'" }

// psTip returns desc, or name when desc is empty: a CompletionResult
// tooltip must not be empty.
func psTip(desc, name string) string {
	if desc == "" {
		return name
	}
	return desc
}
