// Copyright 2026 Revington
// SPDX-License-Identifier: Apache-2.0

package completion

import (
	"bytes"
	"fmt"
	"strings"
)

// writeZsh renders the zsh script (spec 10 req 108): a #compdef function
// dispatching nouns and verbs with _arguments and _describe, one function
// per command whose _arguments specs list its flags in --name= form and
// its positionals. An enum flag with modes picks its values from the
// words already on the line.
func writeZsh(b *bytes.Buffer, m *model) {
	p, fn := m.program, "_"+m.ident
	fmt.Fprintf(b, `#compdef %[1]s
# zsh completion for %[1]s
# Generated by '%[1]s completion zsh'; do not edit.
# Install: %[1]s completion zsh > "${fpath[1]}/_%[1]s"

%[2]s() {
    local curcontext=$curcontext state state_descr line ret=1
    typeset -A opt_args
    _arguments -C \
        '1: :_%[2]s_commands' \
        '*:: :->args' && ret=0
    [[ $state == args ]] || return ret
    case $line[1] in
`, p, fn)
	for _, t := range m.tops {
		fmt.Fprintf(b, "    (%s) %s_%s && ret=0 ;;\n", t.name, fn, ident(t.name))
	}
	fmt.Fprintf(b, `    esac
    return ret
}

_%[1]s_commands() {
    local -a commands=(
`, fn)
	for _, t := range m.tops {
		fmt.Fprintf(b, "        %s\n", zshQuote(t.name+":"+t.desc))
	}
	fmt.Fprintf(b, `    )
    _describe -t commands '%[1]s command' commands
}

%[2]s_help() {
    local -a commands=(
`, p, fn)
	for _, t := range m.tops {
		if t.name != helpWord {
			fmt.Fprintf(b, "        %s\n", zshQuote(t.name+":"+t.desc))
		}
	}
	fmt.Fprintf(b, `    )
    if (( CURRENT == 2 )); then
        _describe -t commands '%[1]s command' commands
    elif (( CURRENT == 3 )); then
        case $words[2] in
`, p)
	for _, n := range m.nouns {
		fmt.Fprintf(b, "        (%s) _%s_%s_verbs ;;\n", n.name, fn, ident(n.name))
	}
	b.WriteString("        esac\n    fi\n}\n")

	for _, n := range m.nouns {
		nf := fn + "_" + ident(n.name)
		fmt.Fprintf(b, `
%[1]s() {
    local curcontext=$curcontext state state_descr line ret=1
    typeset -A opt_args
    _arguments -C \
        '1: :_%[1]s_verbs' \
        '*:: :->args' && ret=0
    [[ $state == args ]] || return ret
    case $line[1] in
`, nf)
		for _, v := range n.verbs {
			fmt.Fprintf(b, "    (%s) %s_%s && ret=0 ;;\n", v.name, nf, ident(v.name))
		}
		fmt.Fprintf(b, `    esac
    return ret
}

_%[1]s_verbs() {
    local -a verbs=(
`, nf)
		for _, v := range n.verbs {
			fmt.Fprintf(b, "        %s\n", zshQuote(v.name+":"+v.desc))
		}
		fmt.Fprintf(b, "    )\n    _describe -t verbs %s verbs\n}\n", zshQuote(p+" "+n.name+" verb"))
	}

	for _, c := range m.cmds {
		writeZshCommand(b, fn, c)
	}
	fmt.Fprintf(b, `
if [[ $funcstack[1] == %[1]s ]]; then
    %[1]s "$@"
else
    compdef %[1]s %[2]s
fi
`, fn, p)
}

// writeZshCommand renders the function of one command.
func writeZshCommand(b *bytes.Buffer, fn string, c cmdModel) {
	parts := make([]string, 0, len(c.path))
	for _, w := range c.path {
		parts = append(parts, ident(w))
	}
	fmt.Fprintf(b, "\n%s_%s() {\n", fn, strings.Join(parts, "_"))
	for _, f := range c.flags {
		if len(f.modes) == 0 {
			continue
		}
		v := "v_" + ident(f.name)
		fmt.Fprintf(b, "    local -a %s=(%s)\n", v, strings.Join(f.value.values, " "))
		for i, md := range f.modes {
			kw := "if"
			if i > 0 {
				kw = "elif"
			}
			fmt.Fprintf(b, "    %s (( ${words[(I)(-|--)(%s)(|=*)]} )); then\n", kw, strings.Join(md.when, "|"))
			fmt.Fprintf(b, "        %s=(%s)\n", v, strings.Join(md.value.values, " "))
		}
		b.WriteString("    fi\n")
	}
	b.WriteString("    _arguments -S")
	for _, f := range c.flags {
		fmt.Fprintf(b, " \\\n        %s", zshQuote(zshFlagSpec(f)))
	}
	for i, a := range c.args {
		pos := fmt.Sprintf("%d:", i+1)
		if a.repeat {
			pos = "*:"
		}
		if a.optional {
			pos += ":"
		}
		fmt.Fprintf(b, " \\\n        %s", zshQuote(pos+zshMessage(a.name)+":"+zshAction(a.value)))
	}
	b.WriteString("\n}\n")
}

// zshFlagSpec is the _arguments spec of one flag.
func zshFlagSpec(f flagModel) string {
	desc := "[" + zshDesc(f.desc) + "]"
	if !f.takesValue {
		return "--" + f.name + desc
	}
	action := zshAction(f.value)
	if len(f.modes) > 0 {
		action = "{compadd -a v_" + ident(f.name) + "}"
	}
	return "--" + f.name + "=" + desc + ":" + zshMessage(f.placeholder) + ":" + action
}

// zshAction is the _arguments action of a value.
func zshAction(v valueKind) string {
	switch v.token() {
	case "file":
		return "_files"
	case "dir":
		return "_files -/"
	case "none":
		return " "
	default:
		return "(" + strings.Join(v.values, " ") + ")"
	}
}

// zshDesc escapes an option description for the brackets of a spec.
func zshDesc(s string) string {
	return strings.NewReplacer(`\`, `\\`, `[`, `\[`, `]`, `\]`).Replace(s)
}

// zshMessage escapes a message, which ends at an unescaped colon.
func zshMessage(s string) string {
	return strings.NewReplacer(`\`, `\\`, `:`, `\:`).Replace(s)
}

// zshQuote single-quotes s for zsh.
func zshQuote(s string) string { return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'" }

// ident turns a command word into an identifier part.
func ident(s string) string { return strings.ReplaceAll(s, "-", "_") }
